import {
  faHeart,
  faUser,
  faHome,
  faSearch,
  faAdd,
  faEdit,
  faCamera,
  faImage,
  faShop,
  faMessage,
  faBell,
  faBasketShopping,
  faArchive,
  faStar,
  faX,
  faWallet,
  faEraser,
} from '@fortawesome/free-solid-svg-icons';

export const navigationIcons = [
  { icon: faHeart, name: 'fa-solid fa-heart' },
  { icon: faUser, name: 'fa-solid fa-profile' },
  { icon: faHome, name: 'fa-solid fa-home' },
  { icon: faSearch, name: 'fa-solid fa-search' },
  { icon: faAdd, name: 'fa-solid fa-add' },
  { icon: faEdit, name: 'fa-solid fa-edit' },
  { icon: faCamera, name: 'fa-solid fa-camera' },
  { icon: faImage, name: 'fa-solid fa-gallery' },
  { icon: faShop, name: 'fa-solid fa-shop' },
  { icon: faMessage, name: 'fa-solid fa-messages' },
  { icon: faBell, name: 'fa-solid fa-notifications' },
  { icon: faBasketShopping, name: 'fa-solid fa-cart' },
  { icon: faArchive, name: 'fa-solid fa-archive' },
  { icon: faStar, name: 'fa-solid fa-favorites' },
  { icon: faX, name: 'fa-solid fa-close' },
  { icon: faWallet, name: 'fa-solid fa-wallet' },
  { icon: faEraser, name: 'fa-solid fa-clear' },
];
